name: APIsec

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 15 * * 6'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Trigger_APIsec_scan:
    permissions:
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: APIsec scan
        uses: apisec-inc/apisec-run-scan@latest
        with:
          apisec-username: ${{ secrets.apisec_username }}
          apisec-password: ${{ secrets.apisec_password }}
          apisec-project: "VAmPI"
          sarif-result-file: "apisec-results.sarif"
      - name: Import results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./apisec-results.sarif
