name: Dependency Check

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pipenv install safety
        pipenv install pip-audit
      continue-on-error: true

    - name: List installed packages
      run: pipenv run pip list

    - name: Run safety check
      run: pipenv run safety check
      continue-on-error: true

    - name: Run pip-audit
      run: pipenv run pip-audit
      continue-on-error: true
